# Blog settings
permalink: /blog/:title

# My variables
name: Nova Courtois
description: Tech and Thoughts
google_verification: null

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge