title: Nova Skye Courtois
email: novacourtois@gmail.com
description: "I make things. I try not to make things worse."
pronouns: "My pronouns are:"
p1: "they"
p2: "them"
baseurl: ""
url: "http://novacourtois.github.io/"
google_analytics: UA-100887551-2

include: ['_pages']
permalink: /:title/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: _scss
  style: :compressed